//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.06 at 02:06:15 PM EEST 
//


package io.mpa.orm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * 			
 * 
 * <p>Java class for basic-collection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="basic-collection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="convert" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="converter" type="{http://mpa.io/orm/schema}converter"/>
 *           &lt;element name="struct-converter" type="{http://mpa.io/orm/schema}struct-converter"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "basic-collection", propOrder = {
    "convert",
    "converter",
    "structConverter"
})
public class BasicCollection {

    protected String convert;
    protected Converter converter;
    @XmlElement(name = "struct-converter")
    protected StructConverter structConverter;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the convert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConvert() {
        return convert;
    }

    /**
     * Sets the value of the convert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConvert(String value) {
        this.convert = value;
    }

    /**
     * Gets the value of the converter property.
     * 
     * @return
     *     possible object is
     *     {@link Converter }
     *     
     */
    public Converter getConverter() {
        return converter;
    }

    /**
     * Sets the value of the converter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Converter }
     *     
     */
    public void setConverter(Converter value) {
        this.converter = value;
    }

    /**
     * Gets the value of the structConverter property.
     * 
     * @return
     *     possible object is
     *     {@link StructConverter }
     *     
     */
    public StructConverter getStructConverter() {
        return structConverter;
    }

    /**
     * Sets the value of the structConverter property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructConverter }
     *     
     */
    public void setStructConverter(StructConverter value) {
        this.structConverter = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
